@startuml
left to right direction
skinparam linetype polyline
actor Klant

rectangle "Klantenpagina" {
  Klant --> (UC201 - Producten bekijken)
  Klant --> (UC202 - Sorteren op prijs)
  Klant --> (UC203 - Filteren op prijsklasse)
  Klant --> (UC204 - Registreren)
  Klant --> (UC205 - Inloggen)
  Klant --> (UC206 - Product aan winkelmand toevoegen)
  Klant --> (UC207 - Afrekenen)
  Klant --> (UC208 - Bestelgeschiedenis bekijken)
}

@enduml